# permissions for end users to view gcpworkloadidentities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcpworkloadidentity-viewer-role
rules:
- apiGroups:
  - projectx.github.com
  resources:
  - gcpworkloadidentities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projectx.github.com
  resources:
  - gcpworkloadidentities/status
  verbs:
  - get
