---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - projectx.github.com
  resources:
  - tenantbootstraps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projectx.github.com
  resources:
  - tenantbootstraps/finalizers
  verbs:
  - update
- apiGroups:
  - projectx.github.com
  resources:
  - tenantbootstraps/status
  verbs:
  - get
  - patch
  - update
