apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
  annotations:
    iam.gke.io/gcp-service-account: px-tenant-provisioner@tony-sandbox-308422.iam.gserviceaccount.com