# permissions for end users to edit tenantnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantnamespace-editor-role
rules:
- apiGroups:
  - projectx.github.com
  resources:
  - tenantnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projectx.github.com
  resources:
  - tenantnamespaces/status
  verbs:
  - get
