apiVersion: projectx.github.com/v1
kind: TenantNamespace
metadata:
  name: product-namespaces
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  namespaces:
    - product1
    - product2
    - product3